# generated by GPT, should be improved. To understand how to improve them, need to look at more transcripts.
# this is lazy, but ensures that structured outputs should produce different responses!

ADVISOR_MESSAGE_BEGINNINGS = [
    "Alright, let's move on to...",
    "Let's delve a bit deeper into...",
    "Mind if I ask you a few more questions about...",
    "Shifting gears a bit, I'd like to ask about...",
    "Could you tell me a little more about...",
    "Next, I'd like to explore...",
    "Let's talk about...",
    "How about we discuss...",
    "So, tell me about...",
    "Now, regarding...",
    "What about...",
    "Can we talk about...",
    "Moving onto...",
    "I'd like to hear your thoughts on...",
    "To switch gears, could you elaborate on...",
    "Let's pivot and discuss...",
    "I'm curious to hear more about...",
    "To shift our focus slightly, can you tell me about...",
    "Let's explore...",
]
